name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy_staging:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [staging]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Additional steps for building, testing, etc.

      - name: Request review for staging
        if: matrix.environment == 'staging'
        uses: actions/request-reviewer@v2
        with:
          reviewers: 'username' # Replace 'username' with the GitHub username of the reviewer

      - name: Display environment
        run: echo "Deploying to ${{ matrix.environment }} environment"

  deploy_production:
    needs: deploy_staging
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [production]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Additional steps for building, testing, etc.

      - name: Request review for production
        if: matrix.environment == 'production'
        uses: actions/request-reviewer@v2
        with:
          reviewers: 'username' # Replace 'username' with the GitHub username of the reviewer

      - name: Display environment
        run: echo "Deploying to ${{ matrix.environment }} environment"
