name: .NET CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        dotnet-version: [6.0.x, 7.0.x, 8.0.x]
      fail-fast: false
      max-parallel: 3

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish Build Artifacts
      run: dotnet publish -c Release -o out

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-dotnet-app-${{ matrix.os }}-${{ matrix.dotnet-version }}
        path: out/

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download Build Artifacts
      uses: actions/download-artifact@v3
      with:
        name: |
          my-dotnet-app-ubuntu-latest-6.0.x,
          my-dotnet-app-ubuntu-latest-7.0.x,
          my-dotnet-app-ubuntu-latest-8.0.x,
          my-dotnet-app-windows-latest-6.0.x,
          my-dotnet-app-windows-latest-7.0.x,
          my-dotnet-app-windows-latest-8.0.x,
          my-dotnet-app-macos-latest-6.0.x,
          my-dotnet-app-macos-latest-7.0.x,
          my-dotnet-app-macos-latest-8.0.x
        path: my-dotnet-app

    - name: Deploy to Production
      run: echo "Deploying to production..."
      # Add your deployment script here
