name: Deploy to Staging

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: staging
      url: https://example.com/deployment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy
        env:
          API_KEY: ${{ secrets.STAGING_API_KEY }}
        run: |
          echo "Deploying to production with API Key: $API_KEY"
          # Your deployment script here
