name: Create a comment on new lines

on: 
  issues:
    types: [opened]

 jobs:
   comment-with-actions:
     runs-on: ubuntu-latest
     steps:
       - name: "dump github context"
         run: echo "${{ toJson(github.event) }}' | jq
         shell: bash
