# File: .github/workflows/linter.yml
name: Linter Workflow

on:
  workflow_call:
    inputs:
      github-token:
        description: 'GitHub token'
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ inputs.github-token }}
          # Optional: Custom configuration file
          LINTER_RULES_PATH: .github/linters/.super-linter.yml
