name: Secret Demo Workflow

on:
  push:
    branches:
      - master

jobs:
  repository-secrets-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Show Repository Secret
        run: echo "The value of REPOSITORY_SECRET is ${{ secrets.REPOSITORY_SECRET }}"

  organization-secrets-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Show Organization Secret
        run: echo "The value of ORGANIZATION_SECRET is ${{ secrets.ORGANIZATION_SECRET }}"
