name: Composite Lint Code Base

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Run Super Linter
        uses: ./.github/actions/composite-superlinter
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
