name: Composite Lint Code Base

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super Linter
        uses: ./.github/actions/composite_superlinter
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
